---
title: "CV"
output: html_document
---
**Steven DiFalco**  
_Curriculum vitea_

Graduate Student, Department of Natural Resources and the Environment 
University of Connecticut 

## Education

2018 – Present **University of Connecticut**, Storrs, CT

> MS, *Human Dimensions of Roadside Vegetation Management*, Advisor: Dr. Anita Morzillo

2009 – 2013 **SUNY New Paltz**, New Paltz, NY

>BS, *Organismal/Environmental Biology*, Advisor: Dr. David Richardson

## Career

2013 – 2015 **Postdoctoral Research Assistant**, University of Connecticut,
Storrs, CT

> Carry out research duties on NSF Dimensions of Biodiversity project
> “Parallel Evolutionary Radiations in Protea and Pelargonium in the
> Greater Cape Floristic Region.”
>
> Supervisor: Dr. John Silander, Jr.

2009 – 2012 **Research Assistant**, Stony Brook University, Stony Brook,
NY

> Integrated climate change and threatened bird population modeling to
> carry out impact assessments and inform land management decisions on
> Florida military installations.
>
> Supervisor: Dr. H. Resit Akçakaya

2009 **Graduate Assistant**, Stony Brook University, Stony Brook, NY

> Assisted in organizing and carrying out field surveys for long-term
> monitoring of Long Island Pitch Pine demography.
>
> Supervisor: Dr. Jessica Gurevitch

2008 – 2009 **Research Consultant**, Applied Biomathematics, Setauket,
NY

Developed and applied models of population level effects of aquatic
toxins.

Supervisor: Dr. Lev Ginzburg

2005 – 2007 **Research Assistant**, P.A.I.N. Group, McLean Hospital,
Belmont, MA

> Analyze large datasets from neuroimaging research studies on
> neurological pain disorders and maintain computation systems for
> P.A.I.N. research group.
>
> Supervisor: Dr. David Borsook

**Publications (peer-reviewed Ecology)**

**Aiello-Lammens, M.E.**, Boria, R.A, Radosavljevic, A., Anderson, R.P.
2014. *spThin: An R package for spatial thinning of species occurrence
records for use in ecological niche models*. Ecography. In Press.

Pearson, R.G., Stanton, J.C., Shoemaker, K.T., **Aiello-Lammens, M.
E.**, Ersts, P.J., Horning, N., Fordham, D.A., Raxworthy, C.J., Ryu,
H.Y., Mcnees, J., Akçakaya, H.R. 2014 *Life history and spatial traits
predict extinction risk due to climate change*. Nature Climate Change 4:
217–221.

Cahill, A.E.\*, **Aiello-Lammens, M.E.\***, Fisher-Reid, M.C., Hua, X.,
Karanewsky, C.J., Ryu, H.Y., Sbeglia, G.C., Spagnolo, F., Waldron, J.B.,
and Wiens, J.J. 2014. *A review of the causes of warm-edge range limits:
proximate factors and implications for climate change.* Journal of
Biogeography 41: 429-442. (\* These authors contributed equally to this
study)

Watts, M.J., Fordham, D.A., Akçakaya, H.R., **Aiello-Lammens, M.E.**,
and Brook, B.W. 2013. *Tracking metapopulation range margin changes
using geographical centroids of patches weighted by population size and
density*. Ecological Modeling 269: 61-69.

Fordham, D.A., Mellin, C., Russel, B., Akçakaya, H.R., Bradshaw, C.,
**Aiello-Lammens, M.E.**, Caley, M., Connell, S., Mayfield, S.,
Shepherd, S., Brook, B.W. 2013. *Population dynamics can be more
important than physiological limits for determining range shifts under
climate change*. Global Change Biology 19(10): 3224-3237.

Linhoss, A.C., Kiker, G.A., **Aiello-Lammens, M.E.**, Chu-Agor, M.L.,
Convertino, M., Muñoz-Carpena, R., Fischer, and R., Linkov, I.
2013. *Decision analysis for species preservation under sea-level rise*.
Ecological Modelling 263: 264-272

Cahill, A.,\* **Aiello-Lammens, M.E.\*,** Fisher-Reid, M.C., Hua, X.,
Karanewsky, C.J., Ryu, H.Y., Sbeglia, G.C., Spagnolo, F., Waldron, J.B.,
Warsi, O., and Wiens, J.J. 2013. *How does climate change cause
extinction?* Proceedings of the Royal Society B 280: 20121890. (\* These
authors contributed equally to this study)

Lowry, E., Rollinson, E.J., Laybourn, A., Scott, T., **Aiello-Lammens,
M.E.,** Gray, S., Mickely, J., and Gurevitch, J. 2012. *Biological
Invasions: a field synopsis, systematic review and database of the
literature*. Ecology and Evolution 3(1):182-196.

**Aiello-Lammens, M.E.,** Chu-Agor, M. L., Convertino, M., Fischer, R.,
Linkov, I., and Akçakaya, H.R. 2011. *The impact of sea-level rise on
Snowy Plovers in Florida: Integrating hydrological, habitat, and
metapopulation models.* Global Change Biology 17(12): 3644-3654.

Chu-Agor, M.L., Muñoz-Carpena, R., Kiker, G., **Aiello-Lammens, M.E.**,
Akçakaya, H.R., Convertino, M., and Linkov, I. 2011. *Simulating the
fate of Florida Snowy Plovers with sea-level rise: Exploring research
and management priorities with a global uncertainty and sensitivity
analysis perspective*. Ecological Modelling 224(1): 33-47.

**Publications (peer-reviewed Neuroscience)**

Moulton, E.A., Pendse, G., Morris, S., **Aiello-Lammens, M.E.,**
Becerra, L.R., and Borsook, D. 2009. *Segmentally arranged somatotopy
within the face representation of human primary somatosensory cortex*.
Human Brain Mapping 30:757–765.

Lebel, A., Becerra, L.R., Wallin, D., Moulton, E.A., Morris, S., Pendse,
G., Jasciewicz, J., Stein, M., **Aiello-Lammens, M.E.**, Grant, E.,
Berde, C., and Borsook, D. 2008. *fMRI reveals distinct CNS processing
during symptomatic and recovered complex regional pain syndrome in
children*. Brain 131:1854–1879.

Borsook, D., Moulton, E.A., Pendse, G., Morris, S., Cole, S.H.,
**Aiello-Lammens. M.E.,** Scrivani, S., and Becerra, L.R. 2007.
*Comparison of evoked vs. spontaneous tics in a patient with trigeminal
neuralgia (tic doloureux)*. Molecular Pain 3:34.

Moulton, E.A., Pendse, G., Morris, S., Strassman, A., **Aiello-Lammens,
M.E.**, Becerra, L.R., and Borsook, D. 2007. *Capsaicin-induced thermal
hyperalgesia and sensitization in the human trigeminal nociceptive
pathway: An fMRI study*. NeuroImage 35:1586–1600.

**Publications (book chapters)**

Convertino, M., Kiker, G.A., Chu-Agor, M.L., Muñoz-Carpena, R.,
Martinez, C.J., **Aiello-Lammens, M.E.**, Akçakaya, H.R., Linkov, I.
2011. *Integrated modeling to mitigate climate change risk due to
sea-level rise: Imperiled shorebirds on Florida coastal military
installations*. NATO Science for Peace and Security Series C:
Environmental Security 4:433-464.

**Publications (in review)**

Merow, C. Allen, J.M., **Aiello-Lammens, M.E.,** Silander, J.A., Jr.
2014. *Minxent: Methods for using spatially explicit information in
Maxent models of species’ ranges*. Global Ecology and Biogeography

**Aiello-Lammens, M.E.** and Akçakaya, H.R. *Global sensitivity analysis
for impact assessments.* Conservation Biology

**Publications (in preparation)**

**Aiello-Lammens, M.E.,** Merow, C., Kilroy, H., Euston-Brown, D.,
Slingsby, J., Silander, J.A., Jr.. *Processes of community composition
in an environmentally heterogeneous, high biodiversity region*

**Aiello-Lammens, M.E.** *Reconstructing the historical spread of*
Frangula alnus *using herbarium records*

Ariori, C.,\* **Aiello-Lammens, M.E.**, Silander, J.A. Jr.. *Plant
invasion along an urban-to-rural gradient in northeast Connecticut*
(\*M.S. student mentee)

Martinod, K.,\* **Aiello-Lammens, M.E.**, Silander, J.A. Jr.. *Do
Invasive Plant Species Have Different Niche Attributers Than Native
Analogs? Insight from Functional Trait Analysis.* (\*Undergraduate
co-advisee)

**Abstracts **

**Aiello-Lammens, M.E.,** Merow, C., Kilroy, H., Euston-Brown, D.,
Slingsby, J., Silander, J.A., Jr. 2014. *Processes of community
composition in an environmentally heterogeneous, high biodiversity
region.* Poster presentation. Graybill Conference on Modern Statistical
Methods for Ecology. Fort Collins, Colorado.

**Aiello-Lammens, M.E.,** Akçakaya, H.R. 2013. *Global sensitivity
analysis for impact assessments.* Oral presentation. Ecological Society
of America, Minneapolis, Minnesota.

**Aiello-Lammens, M.E.** 2012. *Using herbaria records to examine the
spread of the invasive woody plant Frangula alnus.* Poster presentation.
Ecological Society of America, Portland, Oregon.

**Aiello-Lammens, M.E.,** Akçakaya, H.R., Fischer, R., Convertino, M.,
Chu-Agor, M. L., Martinez, M., and Linkov, I. 2011. *Integrated climate
change and threatened bird population modeling to assess risks from
changes in sea-level and weather patterns*. Oral presentation,
International Congress for Conservation Biology, Edmonton, Alberta,
Canada.

Stanton, J.C., **Aiello-Lammens, M.E.,** and Akçakaya, H.R. 2009.
*Relationship between abundance and range size trends in North American
breeding birds.* Poster presentation, Ecological Society of America,
Albuquerque, New Mexico.

**Book Reviews**

**Aiello-Lammens, M.E. **2013. Review of *Maximum Entropy and Ecology: A
Theory of Abundance, Distribution, and Energetics.* The Quarterly Review
of Biology 88(2):133-134

**Aiello-Lammens, M.E.** 2012. Review of *Practical Computing for
Biologists*. The Quarterly Review of Biology 87(4):372

**Aiello-Lammens, M.E.** 2010. Review of *A Primer of Ecology with R*.
The Quarterly Review of Biology 85(3):350

**Aiello-Lammens, M.E.** 2009. Review of *Ecological Models and Data in
R*. The Quarterly Review of Biology 84(3):288

**Teaching Experience**

Spring 2013 **Teaching Assistant, BEE 552 – Biometry**

> Stony Brook University

-   Prepare and deliver weekly two-hour sessions reviewing course
    material and homework assignments.

-   Assist with writing exam questions.

-   Grade homework assignments and exams.

Fall 2012 **Teaching Assistant, BIO 352 – Ecology Laboratory**

Stony Brook University

-   Assist in revision of lab exercises and development of new lab
    exercises.

-   Independently run multiple lab sections throughout the semester.

-   Prepare and deliver lecture material covering lab activities.

Spring 2012 **Invited Lecturer, Long Island Invasive Species Management
Area Scientific Review Committee Cultivar Subcommittee**

-   Developed and delivered a one-day short course introducing basic
    demographic modeling and applications to invasive species assessment
    and management.

Spring 2011 **Instructor, Short Course on R Software**

Stony Brook University

-   Developed material for a six-session short course on using the R
    software in ecology and evolution research for fellow graduate
    students.

Spring 2009 **Teaching Assistant, SSO 102 – Critical Issues in the
Environment**

Stony Brook University

-   Assisted in development of course materials for First-year Seminar.

-   Independently developed and lead multiple class meetings throughout
    the semester.

Fall 2008 **Lab Instructor, BIO 204 – Fundamentals of Scientific
Inquiry**

Stony Brook University

-   Independently lead weekly three-hour lab sessions.

-   Developed lectures to cover key material to facilitate successful
    labs.

Spring 2008 **Lab Instructor, BIO 356 – Applied Ecology and Conservation
Biology **

Stony Brook University

-   Independently lead weekly three-hour lab sessions.

-   Developed lecture material to cover key topics for weekly lab
    sections.

Fall 2007 **Teaching Assistant, BIO 150 – The Living World**

Stony Brook University

-   Facilitate active learning activities in large lecture course.

-   Grade assignments and research papers.

**Invited Talks**

Mar. 2014 *Using integrated demographic and occurrence models to study
invasive species*. Harvard Forest

Dec. 2013 *Patterns and Processes of the Invasion of Frangula alnus: An
Integrated Model Framework*. Suffolk County Community College

**Awards, Fellowship, Scholarships**

2013 Top Graduate Student Award, The Graduate School at Stony Brook
University

2010 Departmental Service Award, Department of Ecology and Evolution,
Stony Brook University

2009 George C. Williams Award, Department of Ecology and Evolution,
Stony Brook University

2007 – 2010 Presidential Recruitment Fellowship, Stony Brook University

**Service**

2014 – Software Carpentry Instructor

2008 – 2013 Volunteer mechanic, Secretary, and President of Stony Brook
University FreeWheel Bicycle Collective

2010 – 2013 Graduate Student Representative to University Bicycle Use
Committee

2009 – 2011 Departmental Senator for Graduate Student Organization

2010 – 2011 Graduate Student Representative to University Senate Campus
Environment Committee

2010 – 2011 Graduate Student Representative to Department of Ecology and
Evolution Faculty

2009 – 2010 Graduate Student Representative to University Senate
Graduate Council

**Professional Societies **

Society for Conservation Biology (since 2008)

Ecological Society of America (since 2007)

Peer reviewer for Ecology Letters, PLoS ONE, BioScience, Global Change
Biology, Global Ecology and Biogeography, Ecography, Ecological
Modelling, Animal Conservation, Population Ecology, Journal of Mammology